services:
  - type: web
    name: anthropic-mastery-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: MONGODB_HOST
        sync: false
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_DB
        value: anthropic_mastery_db
      - key: MONGODB_AUTH_SOURCE
        value: admin
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 10000
      - key: BACKGROUND_CLUSTERING_ENABLED
        value: true
      - key: CLUSTERING_MESSAGE_THRESHOLD
        value: 1
      - key: CLUSTERING_TIME_THRESHOLD_MINUTES
        value: 5
